name: "Geetanjali Gururaj Gubbewad"
description: 
meta_description: ""
plugins: _plugins

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://geetanjaligg.in'

permalink:   /:title/

# Details for the RSS feed generator
url:            'http://geetanjligg.in'
author:         'geetanjaligg'

flickr:
  cache_dir:       "./_cache/flickr"
  api_key:          dbb73d4857727852c56af56f7380d289
  shared_secret:    2e9344cd6f01362e
  access_token:     72157649176451468-5a63266a133e12a7
  access_secret:    c71e5fb0a7df594e
