name: "geetanjaligg"
description: 
meta_description: ""

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://geetanjaligg.in'

# Details for the RSS feed generator
url:            'blog url'
author:         'geetanjaligg'
